# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2400c53a4c21641707f80e61bd7ead664df33da69cf2ff6b04c0ad9b7269989b136288b3643c061062084cd82a984a777a0b3e09545733467257d71c64048c59

staging:
  secret_key_base: 468bc815a709790560d3884d80bffbe2a2570ee46bb8d8ccd305d3bab5a4cff143d23b69cc16a35a1aeeb01754e57c9a6383866442ffa1c1d4a79e4c9a00d958

test:
  secret_key_base: 2d683800f36a6ebc78d9a2f78d1aa155e8e7faa4602b9026adc61ea3f74565afa3fcb893f56b1e57426c5b9ec837834f3cfc89004300635ff12c3cab537594c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
